Feature ETP-13: add pipeline for testing
etendosoftware/etendo_ui_library pull request #1
Opened 2024-08-28 17:41 UTC by LucasAguirre99

A new pipeline has been added to check the status of the repository and make the relevant tests, and 2 scripts have been added to publish the status and to obtain more information about the commits

2024-08-28 18:06 UTC, valeg-etendo requested changes

2024-08-28 18:06 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +                                    sh "git checkout ${GIT_BRANCH}"
```suggestion
                                    sh "git checkout ${GIT_COMMIT}"
```

2024-08-28 18:06 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +        CONTEXT_BUILD       = "Etendo UI Library CI"
```suggestion
        CONTEXT_BUILD       = "Etendo UI Library Tests"
```

2024-08-28 18:06 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +                                        sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_SUCCESS} \"Build Success\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
Not neccessary
```suggestion
```

2024-08-28 18:06 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +                                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_PENDING} \"Starting Build\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```suggestion
                                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_PENDING} \"Running Tests\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```

2024-08-28 18:06 UTC, valeg-etendo commented on pipelines/Jenkinsfile
>                              withCredentials([sshUserPrivateKey(credentialsId: 'my-credentials', keyFileVariable: 'keyfile')]) {
```suggestion
sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_PENDING} \"Starting Build\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
                            withCredentials([sshUserPrivateKey(credentialsId: 'my-credentials', keyFileVariable: 'keyfile')]) {
```

2024-08-28 18:06 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +                                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_FAILURE} \"Build failed\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```suggestion
```

2024-08-28 18:06 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +                              sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_FAILURE} \"Build failed\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```suggestion
```

2024-08-28 18:06 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_SUCCESS} \"Build Successful\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```suggestion
                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_SUCCESS} \"Tests Successful\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```

2024-08-28 18:06 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_FAILURE} \"Build Unstable\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```suggestion
                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_FAILURE} \"Test Failed\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```

2024-08-30 12:37 UTC, valeg-etendo requested changes

2024-08-30 12:37 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +                                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_PENDING} \"Running Build\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```suggestion
                                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_PENDING} \"Running Tests\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```

2024-08-30 12:37 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_FAILURE} \"Test Failed\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```suggestion
                sh "./pipelines/utils/build-update.sh ${REPO_NAME} ${COMMIT_STATUS_FAILURE} \"Tests Failed\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
```

2024-08-30 13:23 UTC, valeg-etendo approved these changes

2024-08-30 14:27 UTC, RomanMagnoli approved these changes

2024-08-30 14:59 UTC, merged