Feature ETP-13: fix github credentials
etendosoftware/etendo_ui_library pull request #2
Opened 2024-08-30 18:22 UTC by LucasAguirre99

In this case, the github credentials were being used the old way with withcredencials, so they were changed to be defined as environment variables

2024-09-02 12:30 UTC, valeg-etendo requested changes

2024-09-02 12:30 UTC, valeg-etendo commented on pipelines/Jenkinsfile
>          REPO_URL            = "git@github.com:etendosoftware/etendo_ui_library.git"
```suggestion
        REPO_URL_SSH        = "git@github.com:etendosoftware/etendo_ui_library.git"
```

2024-09-02 12:30 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +        URL_REPO            = "https://github.com/etendosoftware/etendo_ui_library"
```suggestion
        REPO_URL            = "https://github.com/etendosoftware/etendo_ui_library"
```

2024-09-02 12:30 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +                                    env.URL_ORG_GITHUB = "${URL_REPO}"
```suggestion
```

2024-09-02 12:30 UTC, valeg-etendo commented on pipelines/Jenkinsfile
>                                      def commitInfoTemplate = infoCommit.generateCommitInfo(env.URL_ORG_GITHUB, null, REPO_NAME, true, null)
```suggestion
                                    def commitInfoTemplate = infoCommit.generateCommitInfo(env.URL_REPO, null, REPO_NAME, true, null)
```

2024-09-02 13:00 UTC, valeg-etendo requested changes

2024-09-02 13:00 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +        REPO_URL_SSH            = "git@github.com:etendosoftware/etendo_ui_library.git"
```suggestion
        REPO_URL_SSH        = "git@github.com:etendosoftware/etendo_ui_library.git"
```

2024-09-03 12:17 UTC, valenvivaldi approved these changes

2024-09-03 13:26 UTC, valeg-etendo approved these changes

2024-09-03 13:29 UTC, merged